---
forward_location: "/home/forward"

ssh_gateway_location: "{{ streisand_gateway_location }}/ssh"

ssh_markdown_instructions: "{{ ssh_gateway_location }}/index.md"
ssh_html_instructions: "{{ ssh_gateway_location }}/index.html"

ssh_rsa_key: "{{ ssh_gateway_location }}/streisand_rsa"
ssh_putty_rsa_key: "{{ ssh_gateway_location }}/streisand_rsa.ppk"
