---
- name: Use the AMI ID for Tokyo when the region is ap-northeast-1
  set_fact: aws_ami_id="{{ aws_kali_tokyo_ami_id }}"
  when: aws_region == "ap-northeast-1"

- name: Use the AMI ID for Singapore when the region is ap-southeast-1
  set_fact: aws_ami_id="{{ aws_kali_signapore_ami_id }}"
  when: aws_region == "ap-southeast-1"

- name: Use the AMI ID for Sydney when the region is ap-southeast-2
  set_fact: aws_ami_id="{{ aws_kali_sydney_ami_id }}"
  when: aws_region == "ap-southeast-2"

- name: Use the AMI ID for Ireland when the region is eu-west-1
  set_fact: aws_ami_id="{{ aws_kali_ireland_ami_id }}"
  when: aws_region == "eu-west-1"

- name: Use the AMI ID for Frankfurt when the region is eu-central-1
  set_fact: aws_ami_id="{{ aws_kali_frankfurt_ami_id }}"
  when: aws_region == "eu-central-1"

- name: Use the AMI ID for Sao Paulo when the region is sa-east-1
  set_fact: aws_ami_id="{{ aws_kali_sao_paulo_ami_id }}"
  when: aws_region == "sa-east-1"

- name: Use the AMI ID for Northern Virginia when the region is us-east-1
  set_fact: aws_ami_id="{{ aws_kali_virginia_ami_id }}"
  when: aws_region == "us-east-1"

- name: Use the AMI ID for Northern California when the region is us-west-1
  set_fact: aws_ami_id="{{ aws_kali_california_ami_id }}"
  when: aws_region == "us-west-1"

- name: Use the AMI ID for Oregon when the region is us-west-2
  set_fact: aws_ami_id="{{ aws_kali_oregon_ami_id }}"
  when: aws_region == "us-west-2"
