---
- name: Remove the 'kalify' SSH key from Amazon if it already exists. This is to prevent problems if two people with two different keys are sharing the same AWS account.
  ec2_key: name=kalify-ssh
           state=absent
           aws_access_key="{{ aws_access_key }}"
           aws_secret_key="{{ aws_secret_key }}"
           region="{{ aws_region }}"
           wait=yes

- name: Get the default SSH key
  command: cat ~/.ssh/id_rsa.pub
  register: ssh_key

- name: Add the SSH key to Amazon under the name of 'kalify-ssh'
  ec2_key: name=kalify-ssh
           key_material="{{ ssh_key.stdout }}"
           aws_access_key="{{ aws_access_key }}"
           aws_secret_key="{{ aws_secret_key }}"
           region="{{ aws_region }}"
           wait=yes

# Determine which AMI should be used based on the chosen region
- include: determine-ami-id.yml

- name: Create the EC2 instance
  local_action:
    module: ec2
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    instance_type: "{{ aws_instance_type }}"
    image: "{{ aws_ami_id }}"
    vpc_subnet_id: "{{ aws_vpc_subnet_id }}"
    region: "{{ aws_region }}"
    key_name: kalify-ssh
    group: "{{ aws_security_group }}"
    instance_tags:
      Name: "{{ aws_instance_name }}"
    wait: yes
  register: kalify_server

- name: Wait until the server has finished booting and OpenSSH is accepting connections
  wait_for: host={{ kalify_server.instances[0].public_ip }}
            port=22
            search_regex=OpenSSH
            timeout=300

- name: Create the in-memory inventory group
  add_host: name={{ kalify_server.instances[0].public_ip }}
            groups=kalify-host

- name: Set the kalify_ipv4_address variable
  set_fact: kalify_ipv4_address="{{ kalify_server.instances[0].public_ip }}"

- name: Set the kalify_server_name variable
  set_fact: kalify_server_name="{{ aws_instance_name }}"
