---
- name: Provision the EC2 Server
# ==============================
  hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    regions:
      "1": "ap-northeast-1"
      "2": "ap-southeast-1"
      "3": "ap-southeast-2"
      "4": "eu-west-1"
      "5": "eu-central-1"
      "6": "sa-east-1"
      "7": "us-east-1"
      "8": "us-west-1"
      "9": "us-west-2"
    metapackages:
      "1": "kali-linux-full"
      "2": "kali-linux-top10"
      "3": "kali-linux-all"
      "4": "kali-linux-forensic"
      "5": "kali-linux-gpu"
      "6": "kali-linux-pwtools"
      "7": "kali-linux-voip"
      "8": "kali-linux-web"


  # This variable file is included so the ec2-security-group role knows
  # which port to open for SSH
  vars_files:
    - roles/ssh/defaults/main.yml

  vars_prompt:
    - name: "aws_region_var"
      prompt: >
        What region should the server be located in?
          1. Asia Pacific     (Tokyo)
          2. Asia Pacific     (Singapore)
          3. Asia Pacific     (Sydney)
          4. EU               (Ireland)
          5. EU               (Frankfurt)
          6. South America    (Sao Paulo)
          7. US East          (Northern Virginia)
          8. US West          (Northern California)
          9. US West          (Oregon)
        Please choose the number of your region. Press enter for default (#3) region.
      default: "3"
      private: no

    - name: "aws_instance_name_var"
      prompt: "\nWhat should the server be named? Press enter for default (kali).\n"
      default: "kali"
      private: no

    - name: "aws_access_key_var"
      prompt: "\n\nThe following information can be found in the IAM Management Console.\nhttps://console.aws.amazon.com/iam/home?#security_credential\n\nWhat is your AWS Access Key?\n"
      private: no

    - name: "aws_secret_key_var"
      prompt: "\nWhat is your AWS Secret Key?\n"
      private: no

    - name: "aws_vpc_id_var"
      prompt: "\nWhat is your AWS VPC ID to launch the instance in for this region? Press enter for default (default).\n"
      default: null
      private: no

    - name: "aws_vpc_subnet_id_var"
      prompt: "\nWhat is your AWS VPC Subnet ID to launch the instance in? Press enter for default (default).\n"
      default: null
      private: no

    - name: "kali_metapackage_var"
      prompt: >
        Which Kali Linux metapackage would you like to install:
          1. Standard (9.0 GB)
          2. Top 10 security tools (3.5 GB)
          3. Everything (15 GB)
          4. Forensics tools. (3.1GB)
          5. GPU utilities. (4.8GB)
          6. Cracking utilities as well as GPU tools. (6.0GB)
          7. VOIP testing and research tools. (1.8GB)
          8. Web application hacking tools. (4.9GB)
        Please choose the number of your metapackage. Press enter for default (#1) metapackage.
      default: "1"
      private: no

    - name: "confirmation"
      prompt: "\nKalify will now set up your server. This will take some time (1 hour or more) depending on the Kali metapackage you selected.\nPress Enter to begin setup...\n"

  pre_tasks:
    - name: Set the AWS Region fact
      set_fact: aws_region={{ regions[aws_region_var] }}

    - name: Set the AWS Instance Name fact
      set_fact: aws_instance_name={{ aws_instance_name_var }}

    - name: Set the AWS Access Key fact
      set_fact: aws_access_key={{ aws_access_key_var }}

    - name: Set the AWS Secret Key fact
      set_fact: aws_secret_key={{ aws_secret_key_var }}

    - name: Set the AWS VPC ID
      set_fact: aws_vpc_id={{ aws_vpc_id_var }}

    - name: Set the AWS VPC Subnet ID
      set_fact: aws_vpc_subnet_id={{ aws_vpc_subnet_id_var }}

    - name: Set the Kali Linux Metapackage
      set_fact: kali_metapackage={{ metapackages[kali_metapackage_var] }}

  roles:
    - genesis-amazon

- name: Bootstrap the host so it can be managed by ansible
# ========================================================
  hosts: kalify-host
  gather_facts: no

  remote_user: admin
  sudo: yes

  roles:
    - bootstrap

- name: Configure the Server and install required software
# ========================================================
  hosts: kalify-host

  remote_user: admin
  sudo: yes

  roles:
    - common
    - metapackage
